version: '3.4'

services:
  selenium-runner:
    container_name: selenium-runner
    image: selenium/standalone-firefox:3.141.59
    ports:
      - "4444:4444"
    shm_size: '2gb'
  test-runner:
    container_name: hotel-booking-runner
    depends_on:
      - selenium-runner
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./TestResults:/src/HotelBooking.UITests/TestResults